var SMTH = SMTH || {};
SMTH.CONTAINER = {
	PIPES: [],
	"PLAY_STATE": null
};

SMTH.PLAY_STATE = {
	"PLAY_STATE_IDEAL": 0,
	"PLAY_STATE_ROTATING": 1,
	"PLAY_STATE_KILLING": 2
};


SMTH.STATUS = SMTH.STATUS || {};
SMTH.STATUS.CURRENT_LEVEL = null;